### ISSUE TITLE
Issue in csv script (gen_zincid_smile_csv.py)

### ISSUE THREAD

**Issue by chetankm1992** [rasbt/smilite#5]
The backend on **line 15** is hard coded in the file `gen_zincid_smile_csv.py` which need to be updated.

`smilite.generate_zincid_smile_csv(in_csv, out_csv,
                                      print_progress_bar=True, backend='zinc12')`

backend should be set to backend as it is done in `lookup_zincid.py` file in command line scripts. Otherwise it gives invalid ZINC ID error.

`smilite.generate_zincid_smile_csv(in_csv, out_csv,
                                      print_progress_bar=True, backend=backend)`

Its not a question, its a small fix.

**Comment by rasbt** [comment]
Good call, thanks for the note! Should be fixed now via #6

**Comment by chetankm1992** [comment]
On this note, is there a way to download whole ZINC dataset with all the information or any parser to download information such as Gene information, SMILES, InChI, etc.

**Comment by rasbt** [comment]
If I remember correctly, I the CSV files contain SMILES info at least. Not sure what you mean by Gene Information because these molecules are small organic molecules not proteins. 

To download a CSV file with all sorts of info for all ZINC molecules, you can click on "All Purchasable" at http://zinc12.docking.org/browse/subsets/


![Screen Shot 2020-07-26 at 8 16 54 AM](https://user-images.githubusercontent.com/5618407/88479991-c9cc5e00-cf18-11ea-9a3c-124acd958e18.png)

And then click on properties:

![Screen Shot 2020-07-26 at 8 17 31 AM](https://user-images.githubusercontent.com/5618407/88479999-d5b82000-cf18-11ea-83a5-c362fbd74a2e.png)

After downloading, you can rename the file from .xls to .csv.

**Comment by chetankm1992** [comment]
Thank you so much for the details.

By gene information I mean that whether there is any information if that small molecule binds to a particular protein, and their gene symbol is provided. for example this information here:
![image](https://user-images.githubusercontent.com/28491233/88595125-6df4f880-d030-11ea-8277-fd39550b057d.png)

**Comment by rasbt** [comment]
Oh I see. Sorry, but this is currently not part of the information being fetched. Could be added in future though.

**Comment by chetankm1992** [comment]
Thank you so much. If you have any update regarding this in future, please let me know.
